# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: AzureAppServiceSettings@1
  inputs:
    azureSubscription: 'Resource Manager - Tailspin - Space Game'
    appName: 'welkadimAzueDevOps'
    resourceGroupName: 'AzureDevOpsDemo'
    appSettings: |
      [
         {
          "name": "LeaderboardFunctionUrl",
          "value": "https://welkadimdevopsfun.azurewebsites.net/",
          "slotSetting": false
         }
      ]
